server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${EUREKA:localhost}:8761/eureka/
  instance:
    hostname: ${EUREKA:localhost}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: leche-service
          uri: lb://leche-service
          predicates:
            - Path=/leches/**
        - id: turno-service
          uri: lb://turno-service
          predicates:
            - Path=/turnos/**
        - id: proveedor-service
          uri: lb://proveedor-service
          predicates:
            - Path=/proveedores/**
        - id: pagoproveedor-service
          uri: lb://pagoproveedor-service
          predicates:
            - Path=/pagoproveedores/**